### ISSUE TITLE
upgrading Xquartz breaks loon package

### ISSUE THREAD

**Issue by jonesparg** [great-northern-diver/loon#146]
I'm not a developer, but I'll do my best here.   While I was working with spline functions I discovered this fabulous loon package, followed the vignette, and had a lot of fun. Loon apparently calls Xquartz(), and Xquartz() and asked me to install/upgrade the package, so I did at the end of my session.  When I tried to start up again, loon would no longer work.  It hangs RStudio and you have to force RStudio to quit  otherwise it will just sit there waiting for something until hell freezes over.

Steps to reproduce:

1. Upgrade Xquartz
2.  load loon library and get ready for fun
3.  R hangs indefinitely during the load, giving the following message:
> library(loon)
Loading required package: tcltk
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Note that it worked just fine before the upgrade - nothing hung, and everything ran beautifully.  

![Screen Shot 2021-04-11 at 11 04 27 PM](https://user-images.githubusercontent.com/22328360/114335207-4be9ca80-9b1a-11eb-85c1-8a7f00b950df.png)

**Comment by jonesparg** [comment]
A suggestion I found was to install Xcode toolkit, which I did.  Then I restarted everything and tried again. I no longer get the error message, but RStudio still hangs indefinitely, which means I still can't use this fabulous package.  I wish I'd never upgraded XQuartz!

**Comment by jonesparg** [comment]
Resolved by re-installing Xquartz and doing a clean reboot.  Now it works.  But what a strange error.

**Comment by rwoldford** [comment]
Sorry, was preparing classes for end of term ... so didn't read this until today.
Glad you got everything resolved.

If you are a ggplot fan, you might try loon.ggplot too.

Should be new releases of both before the end of the month on CRAN.
